# Generated by Django 3.2.9 on 2021-11-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='all_day',
            new_name='allDay',
        ),
        migrations.RenameField(
            model_name='calendar',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='calendar',
            old_name='start_date',
            new_name='start',
        ),
    ]
